apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ai-deployment
  labels:
    name:  ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ai
  template:
    metadata:
      labels:
        app:  ai
    spec:
      containers:
      - image:  329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/ai-service
        imagePullPolicy: Always
        name:  ai-service-container
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 3001
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 3001
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name:  auth
              key:  ACCESS_TOKEN_SECRET    
        - name:  MONGODB_URI
          valueFrom:
            secretKeyRef:
              name:  database
              key:  AI_DB
        - name:  MESSAGE_BROKER_URL
          valueFrom:
            secretKeyRef:
              name:  message-broker
              key:  MESSAGE_BROKER_URL    
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name:  ai
              key:  MISTRAL_API_KEY

        - name: LANGSMITH_TRACING
          valueFrom:
            secretKeyRef:
              name:  ai
              key:  LANGSMITH_TRACING
        - name: LANGSMITH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name:  ai
              key:  LANGSMITH_ENDPOINT
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name:  ai  
              key:  LANGSMITH_API_KEY
        - name: LANGSMITH_PROJECT
          valueFrom:
            secretKeyRef: 
              name:  ai
              key:  LANGSMITH_PROJECT
        
        ports:
        - containerPort:  3001
          name:  ai-service-port
      